package com.epam.jwd.web.dao.extractor;

public enum TypeExtractor {
    USER_EXTRACTOR,
    ORDER_EXTRACTOR,
    ADDRESS_EXTRACTOR,
    BONUS_EXTRACTOR,
    CARD_EXTRACTOR,
    CATEGORY_EXTRACTOR,
    CITY_EXTRACTOR,
    INGREDIENT_EXTRACTOR,
    MEAL_EXTRACTOR,
    ROLE_EXTRACTOR,
    STATUS_EXTRACTOR,
    STREET_EXTRACTOR,
    USER_DETAILS_EXTRACTOR
}
