package com.epam.jwd.web.model;

public enum TypeModel {
    ADDRESS_MODEL,
    BONUS_MODEL,
    CAFE_ORDER_MODEL,
    CARD_MODEL,
    CATEGORY_MODEL,
    CITY_MODEL,
    INGREDIENT_MODEL,
    MEAL_MODEL,
    ROLE_MODEL,
    STATUS_MODEL,
    STREET_MODEL,
    USER_MODEL,
    USER_DETAILS_MODEL,
    ORDER_ELEMENT
}
